fetchListContents() {
  return [
    {
      "title": "Make You Mine",
      "contents": "Well, I will call you darlin' and everything will be okay",
      "author": "Tony Stark",
      "following": true,
      "cake": true,
      "comments": [
        "Hello",
        "Namaste",
      ],
      "readersChoice": false,
      "bookmarked": true,
      "date": "10/12/12",
    },
    {
      "title": "Before You Go",
      "contents":
          "Was there something I could've said to make your heart beat better?",
      "author": "Brad Pitt",
      "following": false,
      "cake": true,
      "comments": [
        "World",
        "Namaste",
      ],
      "readersChoice": true,
      "bookmarked": false,
      "date": "1/1/1",
    },
    {
      "title": "Make You Mine",
      "contents": "Well, I will call you darlin' and everything will be okay",
      "author": "Tony Stark",
      "following": true,
      "cake": true,
      "comments": [
        "Hello",
        "Namaste",
      ],
      "readersChoice": false,
      "bookmarked": true,
      "date": "10/12/12",
    },
    {
      "title": "Before You Go",
      "contents":
          "Was there something I could've said to make your heart beat better?",
      "author": "Brad Pitt",
      "following": false,
      "cake": true,
      "comments": [
        "World",
        "Namaste",
      ],
      "readersChoice": true,
      "bookmarked": false,
      "date": "1/1/1",
    },{
      "title": "Make You Mine",
      "contents": "Well, I will call you darlin' and everything will be okay",
      "author": "Tony Stark",
      "following": true,
      "cake": true,
      "comments": [
        "Hello",
        "Namaste",
      ],
      "readersChoice": false,
      "bookmarked": true,
      "date": "10/12/12",
    },
    {
      "title": "Before You Go",
      "contents":
          "Was there something I could've said to make your heart beat better?",
      "author": "Brad Pitt",
      "following": false,
      "cake": true,
      "comments": [
        "World",
        "Namaste",
      ],
      "readersChoice": true,
      "bookmarked": false,
      "date": "1/1/1",
    },{
      "title": "Make You Mine",
      "contents": "Well, I will call you darlin' and everything will be okay",
      "author": "Tony Stark",
      "following": true,
      "cake": true,
      "comments": [
        "Hello",
        "Namaste",
      ],
      "readersChoice": false,
      "bookmarked": true,
      "date": "10/12/12",
    },
    {
      "title": "Before You Go",
      "contents":
          "Was there something I could've said to make your heart beat better?",
      "author": "Brad Pitt",
      "following": false,
      "cake": true,
      "comments": [
        "World",
        "Namaste",
      ],
      "readersChoice": true,
      "bookmarked": false,
      "date": "1/1/1",
    },{
      "title": "Make You Mine",
      "contents": "Well, I will call you darlin' and everything will be okay",
      "author": "Tony Stark",
      "following": true,
      "cake": true,
      "comments": [
        "Hello",
        "Namaste",
      ],
      "readersChoice": false,
      "bookmarked": true,
      "date": "10/12/12",
    },
    {
      "title": "Before You Go",
      "contents":
          "Was there something I could've said to make your heart beat better?",
      "author": "Brad Pitt",
      "following": false,
      "cake": true,
      "comments": [
        "World",
        "Namaste",
      ],
      "readersChoice": true,
      "bookmarked": false,
      "date": "1/1/1",
    },{
      "title": "Make You Mine",
      "contents": "Well, I will call you darlin' and everything will be okay",
      "author": "Tony Stark",
      "following": true,
      "cake": true,
      "comments": [
        "Hello",
        "Namaste",
      ],
      "readersChoice": false,
      "bookmarked": true,
      "date": "10/12/12",
    },
    {
      "title": "Before You Go",
      "contents":
          "Was there something I could've said to make your heart beat better?",
      "author": "Brad Pitt",
      "following": false,
      "cake": true,
      "comments": [
        "World",
        "Namaste",
      ],
      "readersChoice": true,
      "bookmarked": false,
      "date": "1/1/1",
    },{
      "title": "Make You Mine",
      "contents": "Well, I will call you darlin' and everything will be okay",
      "author": "Tony Stark",
      "following": true,
      "cake": true,
      "comments": [
        "Hello",
        "Namaste",
      ],
      "readersChoice": false,
      "bookmarked": true,
      "date": "10/12/12",
    },
    {
      "title": "Before You Go",
      "contents":
          "Was there something I could've said to make your heart beat better?",
      "author": "Brad Pitt",
      "following": false,
      "cake": true,
      "comments": [
        "World",
        "Namaste",
      ],
      "readersChoice": true,
      "bookmarked": false,
      "date": "1/1/1",
    },{
      "title": "Make You Mine",
      "contents": "Well, I will call you darlin' and everything will be okay",
      "author": "Tony Stark",
      "following": true,
      "cake": true,
      "comments": [
        "Hello",
        "Namaste",
      ],
      "readersChoice": false,
      "bookmarked": true,
      "date": "10/12/12",
    },
    {
      "title": "Before You Go",
      "contents":
          "Was there something I could've said to make your heart beat better?",
      "author": "Brad Pitt",
      "following": false,
      "cake": true,
      "comments": [
        "World",
        "Namaste",
      ],
      "readersChoice": true,
      "bookmarked": false,
      "date": "1/1/1",
    },
  ];
}
